### ISSUE TITLE
Adding Articulation - only show same side elements (i.e., left)

### ISSUE THREAD

**Issue by clegarde** [spawaskar-cora/cora-docs#151]
I was adding an articulation for a right fibula, and the options in the list were correct bones, but also included elements from the left side. In the example below, CIL 2003-116 G-05 X-219B 403 is a left tibia, which would not articulate with a right fibula, only another right tibia would. Can we make this so it will only provide same side elements as possible articulations? i.e., it's a right fibula, so only provide right tibia and talus.
![screen shot 2018-05-08 at 9 41 20 pm](https://user-images.githubusercontent.com/7350474/39792990-fdd6f3c4-5308-11e8-9001-169587a4fed3.png)

**Comment by SachinPawaskarUNO** [comment]
@clegarde This issue has been addressed with a new release. Please verify and close issue if verified.

**Comment by clegarde** [comment]
This is still providing left and right elements in the list.

**Comment by fedamann** [comment]
@clegarde pls verify the update

**Comment by clegarde** [comment]
This is still showing left and rights, but not for all elements. In the example below for a left tibia, left and right tali and fibulae are listed, but only the left femur (there is a right femur under 219B).
![screen shot 2018-09-20 at 10 03 49 am](https://user-images.githubusercontent.com/7350474/45827873-fbd95d00-bcbc-11e8-87ae-9593e63b84c2.png)

**Comment by SachinPawaskarUNO** [comment]
@rpernst Has this issue been addressed?

**Comment by clegarde** [comment]
Doesn't appear to be. Still getting the same list of left and right elements for the example above.

**Comment by SachinPawaskarUNO** [comment]
@rpernst please see @clegarde comment above. This has not been addressed as yet. Please take a look as this as soon as possible.

**Comment by SachinPawaskarUNO** [comment]
@clegarde Can you please verify this issue?

**Comment by clegarde** [comment]
GTG
